# Generated by Django 4.2.27 on 2026-01-12

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MarketPoint",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("instrument", models.CharField(db_index=True, max_length=32)),
                ("date", models.DateField(db_index=True)),
                ("value", models.FloatField(blank=True, null=True)),
            ],
            options={
                "unique_together": {("instrument", "date")},
            },
        ),
        migrations.CreateModel(
            name="MarketLatest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("instrument", models.CharField(max_length=32, unique=True)),
                ("category", models.CharField(max_length=32)),
                ("name", models.CharField(max_length=64)),
                ("price", models.FloatField(blank=True, null=True)),
                ("change_pct", models.FloatField(blank=True, null=True)),
                ("as_of", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddIndex(
            model_name="marketpoint",
            index=models.Index(fields=["instrument", "date"], name="markets_mar_instrum_00b071_idx"),
        ),
        migrations.AddIndex(
            model_name="marketlatest",
            index=models.Index(fields=["category", "instrument"], name="markets_mar_categor_49e35c_idx"),
        ),
    ]
